//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Printer.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Demo;

public interface BrokerPrx extends com.zeroc.Ice.ObjectPrx
{
    default void registerClient(ClientPrx clientProxy)
    {
        registerClient(clientProxy, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void registerClient(ClientPrx clientProxy, java.util.Map<String, String> context)
    {
        _iceI_registerClientAsync(clientProxy, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> registerClientAsync(ClientPrx clientProxy)
    {
        return _iceI_registerClientAsync(clientProxy, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> registerClientAsync(ClientPrx clientProxy, java.util.Map<String, String> context)
    {
        return _iceI_registerClientAsync(clientProxy, context, false);
    }

    /**
     * @hidden
     * @param iceP_clientProxy -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_registerClientAsync(ClientPrx iceP_clientProxy, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "registerClient", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeProxy(iceP_clientProxy);
                 }, null);
        return f;
    }

    default void registerServer(ServerPrx serverProxy)
    {
        registerServer(serverProxy, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void registerServer(ServerPrx serverProxy, java.util.Map<String, String> context)
    {
        _iceI_registerServerAsync(serverProxy, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> registerServerAsync(ServerPrx serverProxy)
    {
        return _iceI_registerServerAsync(serverProxy, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> registerServerAsync(ServerPrx serverProxy, java.util.Map<String, String> context)
    {
        return _iceI_registerServerAsync(serverProxy, context, false);
    }

    /**
     * @hidden
     * @param iceP_serverProxy -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_registerServerAsync(ServerPrx iceP_serverProxy, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "registerServer", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeProxy(iceP_serverProxy);
                 }, null);
        return f;
    }

    default void handleClient(String clientId, String requestData)
    {
        handleClient(clientId, requestData, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void handleClient(String clientId, String requestData, java.util.Map<String, String> context)
    {
        _iceI_handleClientAsync(clientId, requestData, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> handleClientAsync(String clientId, String requestData)
    {
        return _iceI_handleClientAsync(clientId, requestData, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> handleClientAsync(String clientId, String requestData, java.util.Map<String, String> context)
    {
        return _iceI_handleClientAsync(clientId, requestData, context, false);
    }

    /**
     * @hidden
     * @param iceP_clientId -
     * @param iceP_requestData -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_handleClientAsync(String iceP_clientId, String iceP_requestData, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "handleClient", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_clientId);
                     ostr.writeString(iceP_requestData);
                 }, null);
        return f;
    }

    default void handleServer(String serverId, String responseData)
    {
        handleServer(serverId, responseData, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void handleServer(String serverId, String responseData, java.util.Map<String, String> context)
    {
        _iceI_handleServerAsync(serverId, responseData, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> handleServerAsync(String serverId, String responseData)
    {
        return _iceI_handleServerAsync(serverId, responseData, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> handleServerAsync(String serverId, String responseData, java.util.Map<String, String> context)
    {
        return _iceI_handleServerAsync(serverId, responseData, context, false);
    }

    /**
     * @hidden
     * @param iceP_serverId -
     * @param iceP_responseData -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_handleServerAsync(String iceP_serverId, String iceP_responseData, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "handleServer", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_serverId);
                     ostr.writeString(iceP_responseData);
                 }, null);
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static BrokerPrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), BrokerPrx.class, _BrokerPrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static BrokerPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), BrokerPrx.class, _BrokerPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static BrokerPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), BrokerPrx.class, _BrokerPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static BrokerPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), BrokerPrx.class, _BrokerPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static BrokerPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, BrokerPrx.class, _BrokerPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static BrokerPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, BrokerPrx.class, _BrokerPrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default BrokerPrx ice_context(java.util.Map<String, String> newContext)
    {
        return (BrokerPrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default BrokerPrx ice_adapterId(String newAdapterId)
    {
        return (BrokerPrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default BrokerPrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (BrokerPrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default BrokerPrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (BrokerPrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default BrokerPrx ice_invocationTimeout(int newTimeout)
    {
        return (BrokerPrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default BrokerPrx ice_connectionCached(boolean newCache)
    {
        return (BrokerPrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default BrokerPrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (BrokerPrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default BrokerPrx ice_secure(boolean b)
    {
        return (BrokerPrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default BrokerPrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (BrokerPrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default BrokerPrx ice_preferSecure(boolean b)
    {
        return (BrokerPrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default BrokerPrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (BrokerPrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default BrokerPrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (BrokerPrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default BrokerPrx ice_collocationOptimized(boolean b)
    {
        return (BrokerPrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default BrokerPrx ice_twoway()
    {
        return (BrokerPrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default BrokerPrx ice_oneway()
    {
        return (BrokerPrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default BrokerPrx ice_batchOneway()
    {
        return (BrokerPrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default BrokerPrx ice_datagram()
    {
        return (BrokerPrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default BrokerPrx ice_batchDatagram()
    {
        return (BrokerPrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default BrokerPrx ice_compress(boolean co)
    {
        return (BrokerPrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default BrokerPrx ice_timeout(int t)
    {
        return (BrokerPrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default BrokerPrx ice_connectionId(String connectionId)
    {
        return (BrokerPrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default BrokerPrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (BrokerPrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::Demo::Broker";
    }
}
